### ISSUE TITLE
Unknown blueprint: suggest

### ISSUE THREAD

**Issue by toranb** [klclee/ember-cli-suggest#4]
I'm using ember-cli 0.1.12 and when I run the command below I get "unknown blueprint"

```
ember generate suggest foobar
```

**Comment by klclee** [comment]
@toranb I think the syntax for generating a component should include a hyphen in the component name.
Can you try something like `ember generate suggest foobar-input`?

I just tried it against ember-cli 0.1.15 and works fine, any chance you can upgrade?

**Comment by toranb** [comment]
Huh still get Unknown blueprint: suggest when doing

ember generate suggest foobar-input

What version of ember-cli are you using w/ success when you run this?

**Comment by davsket** [comment]
Ok, I made a test, I'm using it with ember-cli 0.1.11 and tested again with ember-cli 0.2.0-beta.1.

You should install the addon using **--save-dev**:

```
npm install ember-cli-suggest --save-dev
```

Otherwise ember-cli won't find it.

I'm updating the **Readme.md** :grinning: to clarify this.

**Comment by toranb** [comment]
Ah yes I remember being trolled by that in a past life :) thanks for the quick update!
