### ISSUE TITLE
Example app?

### ISSUE THREAD

**Issue by toranb** [klclee/ember-cli-suggest#5]
Do you happen to have a working example app that uses this project (even w/out the auto generate setup mentioned in my other issue)? This looks like the most promising addon for type-ahead/suggest like behavior.

Thank you in advance

**Comment by klclee** [comment]
Thanks @toranb ! Yea I use it in 2 or my projects currently. I think the issues could be style related. I have added an example project https://github.com/klclee/suggest-example. It has a [typeahead.css](https://github.com/klclee/suggest-example/blob/master/app/styles/typeahead.css) in there that you can mess around with that correlates to the classes used in the component.

In the example I have overwritten the property `suggestStylesOn` in the [component](https://github.com/klclee/suggest-example/blob/master/app/components/country-input.js#L7). This makes the drop down appear, at the right place. I have added the css as part of the blueprint in latest.

**Comment by toranb** [comment]
Perfect ! thanks again!
