### ISSUE TITLE
How to get the typeahead like behavior without delay?

### ISSUE THREAD

**Issue by toranb** [klclee/ember-cli-suggest#6]
Sorry for all the questions today but I'm planning to use this in a real project tomorrow and I'm trying to verify it fits my need/etc :)

On this line in the KeyUp I see you look for a specific key code - is this intentional?

https://github.com/klclee/ember-cli-suggest/blob/master/addon/mixins/suggest.js#L19

Also if I wanted to hack around locally or in a fork ... what would I need to change in the mixin to get a "show me results right away" (without any type of delay or enter key required). Looking for a true type ahead like component that will show (from an in memory list) my results and let me select them.

I assume I can make this work even if I need to fork /work around the opinions you had for the project you wrote this for.

Along these lines - given the requirements I listed above ... does this project have any other "todos" or "beware -known bug/feature" issues not shown yet (that you know of from your experience) ?

Thanks again for such a great addon !

**Comment by klclee** [comment]
@toranb for your questions.

The keycode 27 is the 'esc' key on the keyboard. This is handy shortcut to close the drop down when all your fingers is still on the keyboard and used to use 'esc' as a way to close things. So just a conventions there really. As it is unlikely one will be using the 'esc' key as a search term think you should be ok.

If you want the results to show straight away you can use set `debounceTime` to 0 and `miniumCharLength` to 0 when you use the generated component. So as a example (from the example [project](https://github.com/klclee/suggest-example/blob/master/app/templates/index.hbs#L2)) you will also add these options:

``` hbs
{{country-input placeHolderText='Find a Country' debounceTime=0 selectedFunction='selectedCountry' miniumCharLength=0}}
```

Right now I don't have many todo's the only thing i can really think of is a easier way to deal with the styles, (tidy up supply style sheet) the  and possibly allow to supply custom item renderers (tho is a over kill i think as the component hbs is there to be changed). As to bugs.. please file a PR if you find one I will merge :)

Fell free to fork. But if you have have some great ideas it be good to contribute back to the project as a PR so other people wants this behaviour can also benefit :+1: 

Hope that helps.. happy hacking
